################################################################################
# OPEN SOURCE MODULE
# Remove the comment if you changed the build scripts!
################################################################################

version: 2

jobs:
  build:
    machine: true

    environment:
      NODE_VERSION: 8.9.4

    steps:
      - checkout

      # Prepare

      - run:
          name: Configure NVM
          command: echo '. ${NVM_DIR}/nvm.sh' >> $BASH_ENV
      - run:
          name: Configure Node.js
          command: |
            nvm install ${NODE_VERSION}
            nvm alias default ${NODE_VERSION}
            node --version

      # Dependencies

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Roboter CLI
          command: npm install roboter-cli
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test

      - run:
          name: Run tests
          command: npm run bot
